/**
 * Writes the Apps Script that makes and fills one Google Sheet per event.
 *
 *   npm run sheets:script                 → D:\pyrexiaa\event-sheets.gs
 *   npm run sheets:script -- <out-path>
 *
 * The script is pasted into script.google.com by the Google account that should
 * own the sheets. It does two jobs: `setUp`, run once by hand, makes the folder
 * and the sheets; and `doPost`, published as a web app, is what the Worker
 * calls to find and rewrite them. It runs as the owner, so no Google Cloud
 * project or key is involved at all.
 *
 * The file carries the shared secret, so it is written OUTSIDE the repo by
 * default. Re-running keeps the secret already in the output file, so the
 * Worker's SHEETS_SCRIPT_SECRET stays valid; delete the file to mint a new one.
 *
 * After adding an event: re-run this, paste the new file over the old one,
 * run `setUp` again, and publish a new version of the web app deployment.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { randomBytes } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'

import { sheetEvents, SHEET_TAG } from '../src/jobs/sheets.ts'

const out = resolve(process.argv[2] ?? fileURLToPath(new URL('../../../event-sheets.gs', import.meta.url)))

const previous = existsSync(out) ? /const SECRET = '([0-9a-f]{64})'/.exec(readFileSync(out, 'utf8'))?.[1] : undefined
const secret = previous ?? randomBytes(32).toString('hex')

const events = sheetEvents.map((e) => [e.name, e.territory.code])

const script = `/**
 * PYREXIA 2026: one live Google Sheet per event.
 *
 * Generated by site/api/scripts/event-sheets.mjs. Edit that, not this.
 *
 * ONE-TIME SETUP
 *   1. Pick "setUp" in the toolbar and press Run. Allow the permissions.
 *      It makes a Drive folder with one sheet per event. If it stops at the
 *      six-minute limit, press Run again: it skips sheets that exist.
 *   2. Deploy > New deployment > gear icon > Web app.
 *      Execute as: Me.  Who has access: Anyone.  Deploy, and copy the Web app URL.
 *
 * "Anyone" means anyone can *reach* the URL; every request without SECRET is
 * refused, and nothing is shared from Drive. Do not share this file: SECRET
 * is the password the fest's server uses to write here.
 */

const SECRET = '${secret}'

const FOLDER_NAME = 'PYREXIA 2026 — Event Sheets'
// The server finds each sheet by this label in the file's description, so a
// sheet can be renamed freely. Do not change the description.
const TAG = ${JSON.stringify(SHEET_TAG)}

const EVENTS = [
${events.map((e) => `  ${JSON.stringify(e)},`).join('\n')}
]

/* ------------------------------------------------------------------ *
 * Run once by hand
 * ------------------------------------------------------------------ */

function setUp() {
  const folder = folder_(true)
  PropertiesService.getScriptProperties().setProperty('FOLDER_ID', folder.getId())

  const existing = new Set(listSheets_().map((s) => s.event))

  let made = 0
  for (const [name, vertical] of EVENTS) {
    if (existing.has(name)) continue

    const ss = SpreadsheetApp.create(vertical + ' · ' + name + ' — PYREXIA 2026')
    const sheet = ss.getSheets()[0]
    sheet.setName('Entries')
    sheet.setFrozenRows(1)
    sheet.getRange('1:1').setFontWeight('bold')

    const file = DriveApp.getFileById(ss.getId())
    file.setDescription(TAG + name)
    file.moveTo(folder)
    made++
  }

  Logger.log('Made ' + made + ' new sheet(s); ' + (EVENTS.length - made) + ' already existed.')
  Logger.log('Folder: ' + folder.getUrl())
  Logger.log('Next: Deploy > New deployment > Web app (Execute as: Me, Who has access: Anyone).')
}

/* ------------------------------------------------------------------ *
 * Called by the fest's server
 * ------------------------------------------------------------------ */

function doGet() {
  return json_({ ok: true, service: 'pyrexia-event-sheets' })
}

function doPost(e) {
  let req
  try {
    req = JSON.parse(e.postData.contents)
  } catch (err) {
    return json_({ ok: false, error: 'bad request' })
  }
  if (!req || req.secret !== SECRET) return json_({ ok: false, error: 'forbidden' })

  try {
    if (req.action === 'list') return json_({ ok: true, sheets: listSheets_() })
    if (req.action === 'write') return json_(writeSheet_(String(req.id), req.grid, Number(req.version) || 0))
    return json_({ ok: false, error: 'unknown action' })
  } catch (err) {
    const message = String((err && err.message) || err)
    // A deleted sheet or lost access won't come back by retrying.
    const permanent = /not found|missing|does not exist|access|permission/i.test(message)
    return json_({ ok: false, error: message, retry: !permanent })
  }
}

function listSheets_() {
  const folder = folder_(false)
  const out = []
  const files = folder.getFilesByType(MimeType.GOOGLE_SHEETS)
  while (files.hasNext()) {
    const f = files.next()
    const d = f.getDescription() || ''
    if (d.indexOf(TAG) === 0) out.push({ event: d.slice(TAG.length), id: f.getId() })
  }
  return out
}

/** Replace the Entries tab with grid, and clear whatever lies beyond it. */
function writeSheet_(id, grid, version) {
  if (!Array.isArray(grid) || !grid.length) return { ok: false, error: 'empty grid' }

  const lock = LockService.getScriptLock()
  if (!lock.tryLock(25000)) return { ok: false, error: 'busy', retry: true }
  try {
    const props = PropertiesService.getScriptProperties()
    const key = 'v:' + id
    // Two writes racing: never let the older list land on top of the newer.
    if (version < Number(props.getProperty(key) || 0)) return { ok: true, skipped: true }

    const ss = SpreadsheetApp.openById(id)
    const sheet = ss.getSheetByName('Entries') || ss.getSheets()[0]

    const width = Math.max.apply(null, grid.map((r) => r.length))
    const values = grid.map((r) => {
      const row = r.map(cell_)
      while (row.length < width) row.push('')
      return row
    })
    sheet.getRange(1, 1, values.length, width).setValues(values)

    const lastRow = sheet.getLastRow()
    const lastCol = sheet.getLastColumn()
    if (lastRow > values.length) {
      sheet.getRange(values.length + 1, 1, lastRow - values.length, Math.max(lastCol, width)).clearContent()
    }
    if (lastCol > width) {
      sheet.getRange(1, width + 1, values.length, lastCol - width).clearContent()
    }

    props.setProperty(key, String(version))
    SpreadsheetApp.flush()
    return { ok: true }
  } finally {
    lock.releaseLock()
  }
}

/**
 * Text stays text: without the apostrophe a mobile number loses its leading
 * zero, a date-looking string becomes a date, and a name starting with "="
 * becomes a formula. The apostrophe itself is not shown.
 */
function cell_(v) {
  if (typeof v === 'number') return v
  const s = v == null ? '' : String(v)
  return s === '' ? '' : "'" + s
}

function folder_(create) {
  const id = PropertiesService.getScriptProperties().getProperty('FOLDER_ID')
  if (id) {
    try {
      return DriveApp.getFolderById(id)
    } catch (err) {
      // Folder gone; fall through and look it up by name.
    }
  }
  const found = DriveApp.getFoldersByName(FOLDER_NAME)
  if (found.hasNext()) return found.next()
  if (!create) throw new Error('No sheets folder yet: run setUp first.')
  return DriveApp.createFolder(FOLDER_NAME)
}

function json_(o) {
  return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)
}
`

writeFileSync(out, script)
console.log(`wrote ${out} (${events.length} events, ${previous ? 'kept its existing' : 'new'} secret)`)
