/**
 * Writes the Apps Script that makes and fills the event sheets.
 *
 *   npm run sheets:script                               → D:\pyrexiaa\event-sheets.gs
 *   npm run sheets:script -- --editor someone@gmail.com  (repeatable)
 *   npm run sheets:script -- --out <path>
 *
 * The layout: every vertical gets one spreadsheet with a tab per event, except
 * the verticals in SEPARATE_SHEET_VERTICALS (Velocity), whose events each get a
 * spreadsheet of their own.
 *
 * The script is pasted into script.google.com by the Google account that owns
 * the sheets. `setUp`, run by hand, builds that layout, retires spreadsheets
 * the layout no longer uses, and shares the folder with EDITORS. `doPost`,
 * published as a web app, is what the Worker calls to find and rewrite tabs.
 *
 * The file carries the shared secret and the editors' addresses, so it is
 * written OUTSIDE the repo by default. Re-running keeps both from the existing
 * output file, so the Worker's SHEETS_SCRIPT_SECRET stays valid; delete the
 * file to mint a new secret.
 *
 * After any change: re-run this, paste the file over the script, run `setUp`,
 * then Deploy > Manage deployments > edit > Version: New version > Deploy.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { randomBytes } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'

import {
  ACCOMMODATION_SHEET,
  ACCOMMODATION_SHEET_TITLE,
  sheetEvents,
  SEPARATE_SHEET_VERTICALS,
  SHEET_TAG,
  VERTICAL_TAG,
} from '../src/jobs/sheets.ts'

const args = process.argv.slice(2)
const flag = (name) => args.flatMap((a, i) => (a === name && args[i + 1] ? [args[i + 1]] : []))

const out = resolve(flag('--out')[0] ?? fileURLToPath(new URL('../../../event-sheets.gs', import.meta.url)))
const previous = existsSync(out) ? readFileSync(out, 'utf8') : ''

const secret = /const SECRET = '([0-9a-f]{64})'/.exec(previous)?.[1] ?? randomBytes(32).toString('hex')

const previousEditors = (() => {
  try {
    return JSON.parse(/const EDITORS = (\[.*\])/.exec(previous)?.[1] ?? '[]')
  } catch {
    return []
  }
})()
const editors = [...new Set([...previousEditors, ...flag('--editor')].map((e) => e.trim().toLowerCase()))]
for (const e of editors) {
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e)) throw new Error(`not an email address: ${e}`)
}

// [event, vertical, whether it gets a spreadsheet of its own]
// The rooming list rides this list under a reserved name. It is not an event,
// but it wants the same spreadsheet, the same discovery by tag and the same
// ordered writes, so it is carried as one that owns its own file.
const events = [
  ...sheetEvents.map((e) => [e.name, e.territory.code, SEPARATE_SHEET_VERTICALS.has(e.territory.id)]),
  [ACCOMMODATION_SHEET, ACCOMMODATION_SHEET_TITLE, true],
]

const script = `/**
 * PYREXIA 2026: live Google Sheets for event entries.
 *
 * Generated by site/api/scripts/event-sheets.mjs. Edit that, not this.
 *
 * Layout: one spreadsheet per vertical with a tab per event, except Velocity,
 * where every event has a spreadsheet of its own. All of it in one Drive
 * folder, shared with EDITORS, who can share it onwards.
 *
 * AFTER PASTING A NEW VERSION OF THIS FILE
 *   1. Pick "setUp" in the toolbar and press Run. It builds whatever is
 *      missing and never touches a tab that already exists. If it stops at
 *      the six-minute limit, press Run again.
 *   2. Deploy > Manage deployments > pencil icon > Version: New version >
 *      Deploy. Until you do, the live web app keeps running the old code.
 *
 * FIRST TIME ONLY: Deploy > New deployment > gear > Web app, Execute as: Me,
 * Who has access: Anyone. "Anyone" only means the URL can be reached; every
 * request without SECRET is refused. Do not share this file.
 */

const SECRET = '${secret}'

// Editors of the whole folder. They can add other people themselves.
const EDITORS = ${JSON.stringify(editors)}

const FOLDER_NAME = 'PYREXIA 2026 — Event Sheets'
// The server finds sheets by these labels, not by their names, so
// spreadsheets and tabs can be renamed freely. Do not change descriptions.
const EVENT_TAG = ${JSON.stringify(SHEET_TAG)}
const VERTICAL_TAG = ${JSON.stringify(VERTICAL_TAG)}
// Developer metadata on a tab, naming the event it holds.
const TAB_KEY = 'pyrexia-event'
// The rooming list's reserved name, so its file is titled and tabbed as what
// it is rather than as an event.
const ACCOMMODATION = ${JSON.stringify(ACCOMMODATION_SHEET)}

// [event, vertical, own spreadsheet?]
const EVENTS = [
${events.map((e) => `  ${JSON.stringify(e)},`).join('\n')}
]

/* ------------------------------------------------------------------ *
 * Run by hand
 * ------------------------------------------------------------------ */

function setUp() {
  const folder = folder_(true)
  PropertiesService.getScriptProperties().setProperty('FOLDER_ID', folder.getId())
  const files = tagged_(folder)

  let madeFiles = 0
  let madeTabs = 0
  const opened = {}
  const created = {}

  for (const [name, vertical, own] of EVENTS) {
    if (own) {
      if (files.events[name]) continue
      const title = name === ACCOMMODATION ? vertical : vertical + ' · ' + name
      const ss = SpreadsheetApp.create(title + ' — PYREXIA 2026')
      header_(ss.getSheets()[0].setName(name === ACCOMMODATION ? 'Bookings' : 'Entries'))
      files.events[name] = place_(ss, EVENT_TAG + name, folder)
      madeFiles++
      continue
    }

    if (!files.verticals[vertical]) {
      const ss = SpreadsheetApp.create(vertical + ' — PYREXIA 2026')
      files.verticals[vertical] = place_(ss, VERTICAL_TAG + vertical, folder)
      opened[vertical] = ss
      created[vertical] = ss
      madeFiles++
    }
    const ss = opened[vertical] || (opened[vertical] = SpreadsheetApp.openById(files.verticals[vertical].getId()))
    if (tabsByEvent_(ss)[name]) continue
    const tab = ss.insertSheet(name.slice(0, 100), ss.getSheets().length)
    tab.addDeveloperMetadata(TAB_KEY, name)
    header_(tab)
    madeTabs++
  }

  // A spreadsheet made just now starts with a blank "Sheet1"; once it has
  // event tabs, that one is clutter. Older spreadsheets are left alone: a
  // blank tab there may be one a volunteer just added.
  for (const vertical of Object.keys(created)) {
    const ss = created[vertical]
    const tagged = tabsByEvent_(ss)
    const taggedIds = Object.keys(tagged).map((k) => tagged[k].getSheetId())
    for (const sheet of ss.getSheets()) {
      if (ss.getSheets().length > 1 && taggedIds.indexOf(sheet.getSheetId()) < 0 && sheet.getLastRow() === 0) {
        ss.deleteSheet(sheet)
      }
    }
  }

  // Events that now live as a tab no longer need their old spreadsheet. It
  // goes to Drive's bin (restorable for 30 days); the database still has
  // every entry, and the tab is filled from it within fifteen minutes.
  const ownSheet = {}
  for (const [name, , own] of EVENTS) if (own) ownSheet[name] = true
  let retired = 0
  for (const name of Object.keys(files.events)) {
    if (ownSheet[name]) continue
    files.events[name].setTrashed(true)
    retired++
  }

  // Share the folder: everything inside inherits it, including sheets made
  // later. Editors may share onwards.
  folder.setShareableByEditors(true)
  const current = folder.getEditors().map((u) => u.getEmail().toLowerCase())
  for (const email of EDITORS) {
    if (current.indexOf(email.toLowerCase()) < 0) folder.addEditor(email)
  }
  const refreshed = tagged_(folder)
  for (const key of Object.keys(refreshed.events)) refreshed.events[key].setShareableByEditors(true)
  for (const key of Object.keys(refreshed.verticals)) refreshed.verticals[key].setShareableByEditors(true)

  Logger.log('Made ' + madeFiles + ' spreadsheet(s) and ' + madeTabs + ' tab(s); moved ' + retired + ' old spreadsheet(s) to the bin.')
  Logger.log('Folder editors: ' + (EDITORS.length ? EDITORS.join(', ') : 'none besides you') + '.')
  Logger.log('Folder: ' + folder.getUrl())
  Logger.log('Now: Deploy > Manage deployments > edit > Version: New version > Deploy.')
}

/* ------------------------------------------------------------------ *
 * Called by the fest's server
 * ------------------------------------------------------------------ */

function doGet() {
  return json_({ ok: true, service: 'pyrexia-event-sheets', layout: 'tabs' })
}

function doPost(e) {
  let req
  try {
    req = JSON.parse(e.postData.contents)
  } catch (err) {
    return json_({ ok: false, error: 'bad request' })
  }
  if (!req || req.secret !== SECRET) return json_({ ok: false, error: 'forbidden' })

  try {
    if (req.action === 'list') return json_({ ok: true, sheets: list_() })
    if (req.action === 'write') {
      return json_(write_(String(req.id), Number(req.gid) || 0, req.grid, Number(req.version) || 0))
    }
    return json_({ ok: false, error: 'unknown action' })
  } catch (err) {
    const message = String((err && err.message) || err)
    // A deleted sheet or lost access won't come back by retrying.
    const permanent = /not found|missing|does not exist|access|permission/i.test(message)
    return json_({ ok: false, error: message, retry: !permanent })
  }
}

/** Where every event lives: { event, id, gid }. */
function list_() {
  const files = tagged_(folder_(false))
  const out = []
  for (const [name, vertical, own] of EVENTS) {
    if (!own || !files.events[name]) continue
    // Made with its Entries tab first, which is gid 0; write_ finds it even if moved.
    out.push({ event: name, id: files.events[name].getId(), gid: 0 })
  }
  for (const vertical of Object.keys(files.verticals)) {
    const id = files.verticals[vertical].getId()
    const tabs = tabsByEvent_(SpreadsheetApp.openById(id))
    for (const name of Object.keys(tabs)) out.push({ event: name, id: id, gid: tabs[name].getSheetId() })
  }
  return out
}

/** Replace one event's tab with grid, and clear whatever lies beyond it. */
function write_(id, gid, grid, version) {
  if (!Array.isArray(grid) || !grid.length) return { ok: false, error: 'empty grid' }

  const lock = LockService.getScriptLock()
  if (!lock.tryLock(25000)) return { ok: false, error: 'busy', retry: true }
  try {
    const props = PropertiesService.getScriptProperties()
    const key = 'v:' + id + ':' + gid
    // Two writes racing: never let the older list land on top of the newer.
    if (version < Number(props.getProperty(key) || 0)) return { ok: true, skipped: true }

    const ss = SpreadsheetApp.openById(id)
    let sheet = ss.getSheets().filter((s) => s.getSheetId() === gid)[0]
    if (!sheet) {
      // Never guess inside a vertical's spreadsheet: the first tab there is
      // another event's. Only a one-event spreadsheet may fall back.
      const description = DriveApp.getFileById(id).getDescription() || ''
      if (description.indexOf(VERTICAL_TAG) === 0) {
        return { ok: false, error: 'tab ' + gid + ' not found in ' + description, retry: false }
      }
      sheet = ss.getSheetByName('Entries') || ss.getSheets()[0]
    }

    const width = Math.max.apply(null, grid.map((r) => r.length))
    const values = grid.map((r) => {
      const row = r.map(cell_)
      while (row.length < width) row.push('')
      return row
    })
    sheet.getRange(1, 1, values.length, width).setValues(values)

    const lastRow = sheet.getLastRow()
    const lastCol = sheet.getLastColumn()
    if (lastRow > values.length) {
      sheet.getRange(values.length + 1, 1, lastRow - values.length, Math.max(lastCol, width)).clearContent()
    }
    if (lastCol > width) {
      sheet.getRange(1, width + 1, values.length, lastCol - width).clearContent()
    }

    props.setProperty(key, String(version))
    SpreadsheetApp.flush()
    return { ok: true }
  } finally {
    lock.releaseLock()
  }
}

/* ------------------------------------------------------------------ *
 * Helpers
 * ------------------------------------------------------------------ */

/** The labelled spreadsheets in the folder, bin excluded. */
function tagged_(folder) {
  const events = {}
  const verticals = {}
  const it = folder.getFilesByType(MimeType.GOOGLE_SHEETS)
  while (it.hasNext()) {
    const f = it.next()
    if (f.isTrashed()) continue
    const d = f.getDescription() || ''
    if (d.indexOf(EVENT_TAG) === 0 && !events[d.slice(EVENT_TAG.length)]) events[d.slice(EVENT_TAG.length)] = f
    if (d.indexOf(VERTICAL_TAG) === 0 && !verticals[d.slice(VERTICAL_TAG.length)]) verticals[d.slice(VERTICAL_TAG.length)] = f
  }
  return { events: events, verticals: verticals }
}

/** Event name → its tab, by the metadata setUp attached, in one lookup. */
function tabsByEvent_(ss) {
  const out = {}
  const found = ss.createDeveloperMetadataFinder().withKey(TAB_KEY).find()
  for (const m of found) {
    const sheet = m.getLocation().getSheet()
    if (sheet && !out[m.getValue()]) out[m.getValue()] = sheet
  }
  return out
}

function place_(ss, description, folder) {
  const file = DriveApp.getFileById(ss.getId())
  file.setDescription(description)
  file.moveTo(folder)
  return file
}

function header_(sheet) {
  sheet.setFrozenRows(1)
  sheet.getRange('1:1').setFontWeight('bold')
  return sheet
}

/**
 * Text stays text: without the apostrophe a mobile number loses its leading
 * zero, a date-looking string becomes a date, and a name starting with "="
 * becomes a formula. The apostrophe itself is not shown.
 */
function cell_(v) {
  if (typeof v === 'number') return v
  const s = v == null ? '' : String(v)
  return s === '' ? '' : "'" + s
}

function folder_(create) {
  const id = PropertiesService.getScriptProperties().getProperty('FOLDER_ID')
  if (id) {
    try {
      return DriveApp.getFolderById(id)
    } catch (err) {
      // Folder gone; fall through and look it up by name.
    }
  }
  const found = DriveApp.getFoldersByName(FOLDER_NAME)
  if (found.hasNext()) return found.next()
  if (!create) throw new Error('No sheets folder yet: run setUp first.')
  return DriveApp.createFolder(FOLDER_NAME)
}

function json_(o) {
  return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)
}
`

writeFileSync(out, script)
console.log(
  `wrote ${out}: ${events.length} events, ${previous.includes(secret) ? 'kept its existing' : 'new'} secret, ` +
    `editors ${editors.length ? editors.join(', ') : 'none'}`,
)
